Proyecto/Areas/Productos/Controllers/CategoriasController.cs
using Microsoft.AspNetCore.Mvc;
using Proyecto.Aplicacion.Interfaces;
using Proyecto.Dominio.Entidades;
using Proyecto.Dominio.Entidades.DTOs;
using Proyecto.ViewModels;

namespace Proyecto.Areas.Productos.Controllers
{
    [Area("Productos")]
    public class CategoriasController : Controller
    {
        private readonly ICategoriaService _categoriaService; 

        public CategoriasController(ICategoriaService categoriaService)
        {
            
            _categoriaService = categoriaService; 
        }


        // GET: CategoriasController
        public async Task<IActionResult> Index()
        {
            var categorias = await _categoriaService.ObtenerListadoDeCategoriasAsync();
            var viewModel = new ListadoCategoriaViewModel
            {
               Categorias = categorias
            };
            return View(viewModel);
        }

        // GET: CategoriasController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CategoriasController/Create
        public ActionResult Crear()
        {
            return View();
        }

        // POST: CategoriasController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear(CategoriaModel categoria)
        {
            if (ModelState.IsValid)
            {
                await _categoriaService.CrearCategoriaAsync(categoria);
                return RedirectToAction("Index");
            }
            return View(categoria);
        }

        // GET: CategoriasController/Edit/5
        public async Task<IActionResult> Editar(int id)
        { 
            
            var categoria = await _categoriaService.ObtenerCategoriaPorIdAsync(id);

            if (categoria == null)
            {
                return NotFound();
            }

            var categoriaDTO = _categoriaService.ConvertToDTO(categoria);
           
            return View(categoriaDTO);
        }

        // POST: CategoriasController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(CategoriaDTO dto)
        {
            if (!ModelState.IsValid)
            {
                return View(dto); // <- Devuelves el mismo DTO si hay errores
            }

            // Convertimos el DTO a Model
            var model = _categoriaService.ConvertToModel(dto);

            await _categoriaService.ActualizarCategoriaModelAsync(model);
            return RedirectToAction("Index");
        }


        // GET: CategoriasController/Delete/5
        public async Task<IActionResult> Eliminar(int id)
        {
            var categoria = await _categoriaService.ObtenerCategoriaPorIdAsync(id);
            if (categoria == null)
            {
                return NotFound();
            }

            var categoriaDTO = _categoriaService.ConvertToDTO(categoria);
            return View(categoriaDTO);
        }

        // POST: CategoriasController/Delete/5
        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EliminarConfirmacion(int id, IFormCollection collection)
        {
            var categoria = await _categoriaService.ObtenerCategoriaPorIdAsync(id);
            if (categoria == null)
            {
                return NotFound();
            }

            await _categoriaService.EliminarCategoriaAsync(id);
            return RedirectToAction("Index");
        }
    }
}

Proyecto/Areas/Productos/Views/Categorias/Crear.cshtml
@model Proyecto.Dominio.Entidades.CategoriaModel

@{
    ViewData["Title"] = "Crear Categoría";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Crear Nueva Categoría</h1>

@using (Html.BeginForm("Crear", "Categorias", FormMethod.Post, new { @class = "mt-4" }))
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="col-lg-12 col-md-12 col-sm-12 m-4">
            @Html.LabelFor(Model => Model.Nombre)
            @Html.TextBoxFor(Model => Model.Nombre, new { @class = "form-control", placeholder = "Ingrese el nombre de la categoría" })
            @Html.ValidationMessageFor(Model => Model.Nombre, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12 m-4">
            @Html.LabelFor(Model => Model.Descripcion)
            @Html.TextAreaFor(Model => Model.Descripcion, new { @class = "form-control", placeholder = "Provee una descripción adecuada para la categoría" })
            @Html.ValidationMessageFor(Model => Model.Descripcion, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-12 float-end" id="btnCrear">
            <a class="btn btn-info" asp-action="Index" asp-area="Productos" asp-controller="Categorias">Volver al Inicio</a>
            <button type="submit" class="btn btn-primary">Crear Categoría</button>
        </div>
    </div>


}

Proyecto/Areas/Productos/Views/Categorias/Editar.cshtml
@model Proyecto.Dominio.Entidades.DTOs.CategoriaDTO

@{
    ViewData["Title"] = "Crear Categoría";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Editar Categoría</h1>


@using (Html.BeginForm("Editar", "Categorias", FormMethod.Post, new { @class = "mt-4"}))
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="col-lg-12 col-md-12 col-sm-12 m-4">
            @Html.LabelFor(Model => Model.Nombre)
            @Html.TextBoxFor(Model => Model.Nombre, new { @class = "form-control", placeholder = "Ingrese el nombre de la categoría" })
            @Html.ValidationMessageFor(Model => Model.Nombre, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12 m-4">
            @Html.LabelFor(Model => Model.Descripcion)
            @Html.TextAreaFor(Model => Model.Descripcion, new { @class = "form-control", placeholder = "Provee una descripción adecuada para la categoría" })
            @Html.ValidationMessageFor(Model => Model.Descripcion, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-12 float-end" id="btnCrear">
            <a class="btn btn-info" asp-action="Index" asp-area="Productos" asp-controller="Categorias">Volver al Inicio</a>
            <button type="submit" class="btn btn-primary">Editar Categoría</button>
        </div>
    </div>


}

Proyecto/Areas/Productos/Views/Categorias/Eliminar.cshtml
@model Proyecto.Dominio.Entidades.DTOs.CategoriaDTO

@{
    ViewData["Title"] = "Eliminar Categoría";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Editar Categoría</h1>


@using (Html.BeginForm("Eliminar", "Categorias", FormMethod.Post, new { @class = "mt-4" }))
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="col-lg-12 col-md-12 col-sm-12 m-4">
            @Html.LabelFor(Model => Model.Nombre)
            @Html.TextBoxFor(Model => Model.Nombre, new { @class = "form-control", placeholder = "Ingrese el nombre de la categoría", @disabled = true })
            @Html.ValidationMessageFor(Model => Model.Nombre, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12 m-4">
            @Html.LabelFor(Model => Model.Descripcion)
            @Html.TextAreaFor(Model => Model.Descripcion, new { @class = "form-control", placeholder = "Provee una descripción adecuada para la categoría", @disabled = true })
            @Html.ValidationMessageFor(Model => Model.Descripcion, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-12 float-end" id="btnCrear">
            <a class="btn btn-info" asp-action="Index" asp-area="Productos" asp-controller="Categorias">Volver al Inicio</a>
            <button type="submit" class="btn btn-danger">Eliminar Categoría</button>
        </div>
    </div>


}

Proyecto/Areas/Productos/Views/Categorias/Index.cshtml
@using Proyecto.ViewModels
@model ListadoCategoriaViewModel

@{
    ViewData["Title"] = "Categorías";
}

<h1 class="text-center">Listado de Categorías</h1>
<div class="float-end">
<a class="btn btn-primary" asp-action="Crear" asp-controller="Categorias">Añadir Categoría +</a>

</div>
<hr />
<br />
<table class="table table-bordered">
    <tr>
        <td>ID</td>
        <td>Nombre</td>
        <td>Descripción</td>
        <td>Acciones</td>
    </tr>

    @foreach(var categoria in Model.Categorias)
    {
        <tr>
            <td>@categoria.Id</td>
            <td>@categoria.Nombre</td>
            <td>@categoria.Descripcion</td>
            <td>
                <a class="btn btn-primary" href="@Url.Action("Editar", "Categorias", new { id = categoria.Id })">Editar</a>
                <a class="btn btn-danger" href="@Url.Action("Eliminar", "Categorias", new { id = categoria.Id })">Eliminar</a>
            </td>
        </tr>
    }

</table>