Proyecto/Areas/Productos/Controllers/LibrosController.cs
using Microsoft.AspNetCore.Mvc;
using Proyecto.Aplicacion.Interfaces;
using Proyecto.Dominio.Entidades;
using Proyecto.Dominio.Entidades.DTOs;
using Proyecto.ViewModels;

namespace Proyecto.Areas.Productos.Controllers
{
    [Area("Productos")]
    public class LibrosController : Controller
    {
        private readonly ILibroService _libroService;
        private readonly ICategoriaService _categoriaService;
        private readonly IWebHostEnvironment _env;
        public LibrosController(ILibroService libroService, ICategoriaService categoriaService, IWebHostEnvironment env)
        {
            _libroService = libroService;
            _categoriaService = categoriaService;
            _env = env;
        }
        // GET: LibrosController
        public async Task<IActionResult> Index()
        {
            var libros = await _libroService.ObtenerListadoLibrosAsync();
            var viewModel = new ListadoLibroViewModel()
            {
                Libros = libros
            };
            return View(viewModel);
        }

        // GET: LibrosController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LibrosController/Create
        public async Task<IActionResult> Crear()
        {
            var model = new LibrosModel
            {
                CategoriasList = await _categoriaService.ObtenerListadoDeCategoriasAsync()
            };
            return View(model);
        }

        // POST: LibrosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear(LibrosModel libros, IFormFile? imagen)
        {
           if (!ModelState.IsValid)
            {
                var errores = ModelState.Values.SelectMany(v => v.Errors)
                                       .Select(e => e.ErrorMessage)
                                       .ToList();

                // solo para ver en consola/logs
                foreach (var error in errores)
                {
                    Console.WriteLine(error);
                }

                libros.CategoriasList = await _categoriaService.ObtenerListadoDeCategoriasAsync();
                return View(libros);

            }

            // IMAGEN 

           ModelState.Remove("ImagePath");

            if (imagen != null && imagen.Length > 0)
            {
                var uploads = Path.Combine(_env.WebRootPath, "images");
                if (!Directory.Exists(uploads))
                {
                    Directory.CreateDirectory(uploads);
                }

                var fileName = Guid.NewGuid().ToString() + Path.GetExtension(imagen.FileName);
                var filePath = Path.Combine(uploads, fileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await imagen.CopyToAsync(stream);
                }

                // Guardamos la ruta relativa
                libros.ImagePath = "/images/" + fileName;
            }
            else
            {
                // Si no hay imagen, ponemos una por defecto
                libros.ImagePath = "/images/default.png";
            }
        

            await _libroService.CrearLibroAsync(libros);
            return RedirectToAction("Index");
        }

        // GET: LibrosController/Edit/5
        public async Task<IActionResult> Editar(int id)
        {
            var libro = await _libroService.ObtenerLibroPorIdAsync(id);

            if (libro == null)
            {
                return NotFound();
            }

            var categorias = await _categoriaService.ObtenerListadoDeCategoriasAsync();
   
            var libroDTO = _libroService.ConvertToDTO(libro);
            libroDTO.CategoriasList = categorias;
            return View(libroDTO);
        }

        // POST: LibrosController/Edit/5
        [HttpPost, ActionName("Editar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(LibrosModel libro, IFormFile? imagen, int id)
        {
            if(!ModelState.IsValid)
            {
                var dto = _libroService.ConvertToDTO(libro);
                return View(dto);
            }
            ModelState.Remove("ImagePath");

            if (imagen != null && imagen.Length > 0)
            {
                var uploads = Path.Combine(_env.WebRootPath, "images");
                if (!Directory.Exists(uploads))
                    Directory.CreateDirectory(uploads);

                var fileName = Guid.NewGuid() + Path.GetExtension(imagen.FileName);
                var filePath = Path.Combine(uploads, fileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await imagen.CopyToAsync(stream);
                }

                libro.ImagePath = "/images/" + fileName;
            }
            else
            {
                // Mantener la imagen existente si no se sube ninguna
                Console.WriteLine("Imagen recibida: " + (imagen != null ? imagen.FileName : "NULL"));
                var libroAnterior = await _libroService.ObtenerLibroPorIdAsync(id);
                libro.ImagePath = libroAnterior.ImagePath;
            }

            await _libroService.ActualizarLibroModelAsync(libro);
            return RedirectToAction("Index");
        }

        // GET: LibrosController/Delete/5
        public async Task<IActionResult> Eliminar(int id)
        {
            var libro = await _libroService.ObtenerLibroPorIdAsync(id);
            if (libro == null)
            {
                return NotFound();
            }

            var libroDTO = _libroService.ConvertToDTO(libro);
            return View(libroDTO);
        }

        // POST: LibrosController/Delete/5
        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EliminarConfirmacion(int id, IFormCollection collection)
        {
            var libro = await _libroService.ObtenerLibroPorIdAsync(id);

            if (libro == null)
            {
                return NotFound();
            }

            await _libroService.EliminarLibroAsync(id);
            return RedirectToAction("Index");
        }
    }
}

Proyecto/Areas/Productos/Views/Libros/Crear.cshtml
@model LibrosModel

@{
    ViewData["Title"] = "Crear Libro";
}

<h1 class="text-center">Crear nuevo libro</h1>

<div class="float-end"><a asp-action="Index" asp-controller="Libros" class="btn btn-secondary">Volver al Inicio</a></div>
<hr />
<br />

<form asp-controller="Libros" asp-action="Crear" method="post" class="mt-4" enctype="multipart/form-data">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="container">
            <div class="col-lg-12 col-md-12 col-sm-12 text-center">
                <label>Subir Imagen</label>
                <center>
                    <img class="img-square" id="preview" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Imagen previa" width="70" height="70">
                </center>
                <input type="file" name="imagen" id="imagen" accept="image/jpeg,image/png" />
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12">
                @Html.LabelFor(model => model.CategoriaId)
                @Html.DropDownListFor(model => model.CategoriaId, new SelectList(Model.CategoriasList, "Id", "Nombre"), "--Elige una categoría--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
            </div>

            <div class="col-lg-12 col-md-12 col-sm-12">
                @Html.LabelFor(model => model.ISBN)
                @Html.TextBoxFor(model => model.ISBN, new { @class = "form-control", @placeholder = "Ingresa el ISBN del libro..." })
                @Html.ValidationMessageFor(model => model.ISBN, "", new { @class = "text-danger" })
            </div>

            <div class="col-lg-12 col-md-12 col-sm-12">
                @Html.LabelFor(model => model.Titulo)
                @Html.TextBoxFor(model => model.Titulo, new { @class = "form-control", @placeholder = "Ingresa el título del libro" })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>

            <div class="col-lg-12 col-md-12 col-sm-12">
                @Html.LabelFor(model => model.Autor)
                @Html.TextBoxFor(model => model.Autor, new { @class = "form-control", @placeholder = "Ingresa el autor del libro"})
                @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
            </div>

            <div class="col-lg-12 col-md-12 col-sm-12">
                @Html.LabelFor(model => model.Descripcion)
                @Html.TextAreaFor(model => model.Descripcion, new { @class = "form-control", @placeholder = "Ingresa la descripción del libro..." })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>

            <div class="col-lg-6 col-md-12 col-sm-12">
                @Html.LabelFor(model => model.Precio)
                @Html.TextBoxFor(model => model.Precio, new { @class = "form-control", @placeholder = "Ingresa el precio del libro..." })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>

            <div class="col-lg-6 col-md-12 col-sm-12">
                @Html.LabelFor(model => model.Cantidad)
                @Html.TextBoxFor(model => model.Cantidad, new { @class = "form-control", @placeholder = "Ingresa la cantidad de libros..." })
                @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
            </div>

            <div class="col-lg-6 col-md-12 col-sm-12">
                @Html.LabelFor(model => model.FechaPublicacion)
                @Html.TextBoxFor(model => model.FechaPublicacion, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
                @Html.ValidationMessageFor(model => model.FechaPublicacion, "", new { @class = "text-danger" })
            </div>

            <div class="float-end col-lg-6 col-md-12 col-sm-12">
                
                <button type="submit" class="btn btn-primary mt-4"><i class="bi bi-save"></i> Guardar</button>
            </div>

        </div>
        
</form>
    
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    @{

        <script src="~/js/previsualizarImagen.js" type="text/javascript"></script>
        <script>
            document.getElementById('imagen').addEventListener('change', function (event) {
                        const [file] = event.target.files;
                        if (file) {
                            document.getElementById('preview').src = URL.createObjectURL(file);
                        }
                    });
        </script>

    }
}

Proyecto/Areas/Productos/Views/Libros/Editar.cshtml
@using Proyecto.Dominio.Entidades.DTOs
@model LibrosDTO

@{
    ViewData["Title"] = "Editar Libro";
}

<h1 class="text-center">Editar libro</h1>

<div class="float-end"><a asp-action="Index" asp-controller="Libros" class="btn btn-secondary">Volver al Inicio</a></div>
<hr />
<br />

<form asp-controller="Libros" asp-action="Editar" method="post" class="mt-4" enctype="multipart/form-data">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="container">
             <div class="col-lg-12 col-md-12 col-sm-12 text-center">
                <label>Subir Imagen</label>
                <center>
                    <img class="img-square" id="preview" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Imagen previa" width="70" height="70">
                </center>
                <input type="file" name="imagen" id="imagen" accept="image/jpeg,image/png" />
            </div>

            <div class="col-lg-12 col-md-12 col-sm-12">
                @Html.LabelFor(model => model.CategoriaId)
                @Html.DropDownListFor(model => model.CategoriaId, new SelectList(Model.CategoriasList, "Id", "Nombre"), "--Elige una categoría--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
            </div>

            <div class="col-lg-12 col-md-12 col-sm-12">
                @Html.LabelFor(model => model.ISBN)
                @Html.TextBoxFor(model => model.ISBN, new { @class = "form-control", @placeholder = "Ingresa el ISBN del libro..." })
                @Html.ValidationMessageFor(model => model.ISBN, "", new { @class = "text-danger" })
            </div>

            <div class="col-lg-12 col-md-12 col-sm-12">
                @Html.LabelFor(model => model.Titulo)
                @Html.TextBoxFor(model => model.Titulo, new { @class = "form-control", @placeholder = "Ingresa el título del libro" })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>

            <div class="col-lg-12 col-md-12 col-sm-12">
                @Html.LabelFor(model => model.Autor)
                @Html.TextBoxFor(model => model.Autor, new { @class = "form-control", @placeholder = "Ingresa el autor del libro"})
                @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
            </div>

            <div class="col-lg-12 col-md-12 col-sm-12">
                @Html.LabelFor(model => model.Descripcion)
                @Html.TextAreaFor(model => model.Descripcion, new { @class = "form-control", @placeholder = "Ingresa la descripción del libro..." })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>

            <div class="col-lg-6 col-md-12 col-sm-12">
                @Html.LabelFor(model => model.Precio)
                @Html.TextBoxFor(model => model.Precio, new { @class = "form-control", @placeholder = "Ingresa el precio del libro..." })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>

            <div class="col-lg-6 col-md-12 col-sm-12">
                @Html.LabelFor(model => model.Cantidad)
                @Html.TextBoxFor(model => model.Cantidad, new { @class = "form-control", @placeholder = "Ingresa la cantidad de libros..." })
                @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
            </div>

            <div class="col-lg-6 col-md-12 col-sm-12">
                @Html.LabelFor(model => model.FechaPublicacion)
                @Html.TextBoxFor(model => model.FechaPublicacion, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
                @Html.ValidationMessageFor(model => model.FechaPublicacion, "", new { @class = "text-danger" })
            </div>

            <div class="float-end col-lg-6 col-md-12 col-sm-12">
                <button type="submit" class="btn btn-primary mt-4"><i class="bi bi-save"></i> Editar</button>
            </div>

        </div>
        
</form>
    

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    @{

                <script src="~/js/previsualizarImagen.js" type="text/javascript"></script>
                <script>
                    document.getElementById('imagen').addEventListener('change', function (event) {
                                const [file] = event.target.files;
                                if (file) {
                                    document.getElementById('preview').src = URL.createObjectURL(file);
                                }
                            });
                </script>

    }
}

Proyecto/Areas/Productos/Views/Libros/Eliminar.cshtml
@using Proyecto.Dominio.Entidades.DTOs
@model LibrosDTO

@{
    ViewData["Title"] = "Eliminar Libro";
}

<h1 class="text-center">Editar libro</h1>

<div class="float-end"><a asp-action="Index" asp-controller="Libros" class="btn btn-secondary">Volver al Inicio</a></div>
<hr />
<br />

<form asp-controller="Libros" asp-action="Eliminar" method="post" class="mt-4">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="container">

        <div class="col-lg-12 col-md-12 col-sm-12">
            @Html.LabelFor(model => model.CategoriaId)
            @Html.DropDownListFor(model => model.CategoriaId, new SelectList(Model.CategoriasList, "Id", "Nombre"), "--Elige una categoría--", new { @class = "form-control", @disabled = true})
            @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12">
            @Html.LabelFor(model => model.ISBN)
            @Html.TextBoxFor(model => model.ISBN, new { @class = "form-control", @placeholder = "Ingresa el ISBN del libro...", @disabled = true })
            @Html.ValidationMessageFor(model => model.ISBN, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12">
            @Html.LabelFor(model => model.Titulo)
            @Html.TextBoxFor(model => model.Titulo, new { @class = "form-control", @placeholder = "Ingresa el título del libro", @disabled = true })
            @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12">
            @Html.LabelFor(model => model.Autor)
            @Html.TextBoxFor(model => model.Autor, new { @class = "form-control", @placeholder = "Ingresa el autor del libro", @disabled = true })
            @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12">
            @Html.LabelFor(model => model.Descripcion)
            @Html.TextAreaFor(model => model.Descripcion, new { @class = "form-control", @placeholder = "Ingresa la descripción del libro...", @disabled = true })
            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-6 col-md-12 col-sm-12">
            @Html.LabelFor(model => model.Precio)
            @Html.TextBoxFor(model => model.Precio, new { @class = "form-control", @placeholder = "Ingresa el precio del libro...", @disabled = true })
            @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-6 col-md-12 col-sm-12">
            @Html.LabelFor(model => model.Cantidad)
            @Html.TextBoxFor(model => model.Cantidad, new { @class = "form-control", @placeholder = "Ingresa la cantidad de libros...", @disabled = true })
            @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-6 col-md-12 col-sm-12">
            @Html.LabelFor(model => model.FechaPublicacion)
            @Html.TextBoxFor(model => model.FechaPublicacion, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date", @disabled = true })
            @Html.ValidationMessageFor(model => model.FechaPublicacion, "", new { @class = "text-danger" })
        </div>

        <div class="float-end col-lg-6 col-md-12 col-sm-12">
            <button type="submit" class="btn btn-danger mt-4"><i class="bi bi-trash"></i> Eliminar</button>
        </div>

    </div>

</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Proyecto/Areas/Productos/Views/Libros/Index.cshtml
@using Proyecto.ViewModels
@model ListadoLibroViewModel

@{
    ViewData["Title"] = "Listado de Libros";
}

<h1 class="text-center">Listado de Libros</h1>
<div class="float-end">
    <a class="btn btn-primary" asp-action="Crear" asp-controller="Libros">Añadir Libro +</a>

</div>
<hr />
<br />
<div class="container">
    <table class="table table-bordered">
        <tr>
            <td>Imagen</td>
            <td>ID</td>
            <td>ISBN</td>
            <td>Título</td>
            <td>Autor</td>
            <td>Categoría</td>
            <td>Descripción</td>
            <td>Fecha de Publicación</td>
            <td>Precio</td>
            <td>Cantidad</td>
            <td>Acciones</td>
        </tr>

        @foreach (var libro in Model.Libros)
        {
            <tr>
                <td><img src="@libro.ImagePath" width="50" height="80" /></td>
                <td>@libro.Id</td>
                <td>@libro.ISBN</td>
                <td>@libro.Titulo</td>
                <td>@libro.Autor</td>
                <td>@libro.Categoria.Nombre</td>
                <td>@libro.Descripcion</td>
                <td>@libro.FechaPublicacion</td>
                <td>@libro.Precio EUROS</td>
                <td>@libro.Cantidad</td>
                <td>
                    <a class="btn btn-primary" href="@Url.Action("Editar", "Libros", new { id = libro.Id })">Editar</a>
                    <a asp-area="Productos" asp-controller="Libros" asp-action="Eliminar" asp-route-id="@libro.Id" class="btn btn-danger">Eliminar</a>
                </td>
            </tr>
        }
    </table>
</div>